### ISSUE TITLE
Bug: User Creation Issue on Develop Branch

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1028]
When I try to create any type of user, I get an Uncaught Exception:
```
Uncaught Exception

Undefined variable: form in /home/cabox/workspace/anchor-cms/app/views/users/create.phtml:23

Stack Trace

#0 /home/cabox/workspace/anchor-cms/app/views/users/create.phtml(23): Errors->native(8, 'Undefined varia...', '/home/cabox/wor...', 23, Array)
#1 /home/cabox/workspace/anchor-cms/app/src/View.php(51): require('/home/cabox/wor...')
#2 /home/cabox/workspace/anchor-cms/app/src/Controllers/Admin/Backend.php(52): View->render('users/create', Array)
#3 /home/cabox/workspace/anchor-cms/app/src/Controllers/Admin/Users.php(53): Controllers\Admin\Backend->renderTemplate('layout', 'users/create', Array)
#4 /home/cabox/workspace/anchor-cms/app/src/Kernel.php(90): Controllers\Admin\Users->getCreate(Object(Http\ServerRequest))
#5 /home/cabox/workspace/anchor-cms/app/src/Kernel.php(71): Kernel->handleController('controllers\\adm...')
#6 /home/cabox/workspace/anchor-cms/app/start.php(89): Kernel->getResponse()
#7 /home/cabox/workspace/anchor-cms/web/index.php(8): require('/home/cabox/wor...')
#8 {main}
```
Seems to be an issue with the user creation view

**Comment by saucytomato** [comment]
Sorry, found the issue. When the password is less than 8 characters, the flow breaks.

**Comment by saucytomato** [comment]
I'm just going to close this and fix the issue.

**Comment by daviddarnes** [comment]
@saucytomato got not problems with making an issue and then providing a pull request fix :smile:.

We can't be opening issues for the dev branch when it's still being worked on though.

**Comment by saucytomato** [comment]
I got that message when you replied to my issue with the missing CSS

**Comment by daviddarnes** [comment]
@saucytomato ah cool. Just make sure to reference this issue when you make the pull request :ok_hand:

**Comment by saucytomato** [comment]
Just one question: Where are the full logs stored?

**Comment by daviddarnes** [comment]
@saucytomato not sure, maybe @CraigChilds94 knows?

**Comment by CraigChilds94** [comment]
@saucytomato I don't know much about the `develop` version. @rwarasaurus Should be able to help you.

**Comment by TheBrenny** [comment]
@saucytomato, are you still having an issue? Or do you know if this has been fixed somewhere? If you're still keen on keeping this open, I'll be glad to help out, just... what logs are you talking about? :joy:

**Comment by rwarasaurus** [comment]
Im fixing this today
