### ISSUE TITLE
Bug: setOptions Array

### ISSUE THREAD

**Issue by saucytomato** [anchorcms/anchor-cms#1045]
### Summary

Tried to upgrade to 0.12.1 on server:

### Expected Behaviour

- Site to load normally

### Actual Behaviour

 ```
Uncaught Exception

Argument 1 passed to System\Session::setOptions() must be of the type array, null given, called in /home/u698317652/public_html/system/start.php on line 36

Origin

system/session.php on line 7

Trace

#0 /home/u698317652/public_html/system/start.php(36): System\Session::setOptions(NULL)
#1 /home/u698317652/public_html/index.php(35): require('/home/u69831765...')
#2 {main}
```

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: Unknown
- URL: inkler.ga

**Comment by saucytomato** [comment]
It has to be an issue with upgrading: If you create a new install and change the mysql server to the original after install, it works fine.

**Comment by TheBrenny** [comment]
I'll try replicate this sometime over the weekend and try smash out a fix.

Just confirming: from 0.12.0 to 0.12.1?

**Comment by saucytomato** [comment]
Yes.

**Comment by TheBrenny** [comment]
Is this still bugging you? I've just checked the link provided, and it seems to work...
