### ISSUE TITLE
Develop branch install issues

### ISSUE THREAD

**Issue by chrissound** [anchorcms/anchor-cms#1138]
I understand it's under development but in the event that it is helpful:

On the install process:
```
TypeError

Argument 2 passed to Validation\Rules\Length::setRange() must be of the type integer, string given, called in /var/www/html/vendor/rwarasaurus/validation/src/Rules/Length.php on line 17 in /var/www/html/vendor/rwarasaurus/validation/src/Rules/Length.php:20

Stack Trace

#0 /var/www/html/vendor/rwarasaurus/validation/src/Rules/Length.php(17): Validation\Rules\Length->setRange(3, '')
#1 [internal function]: Validation\Rules\Length->__construct('3,')
#2 /var/www/html/vendor/rwarasaurus/validation/src/ValidatorFactory.php(43): ReflectionClass->newInstanceArgs(Array)
#3 /var/www/html/vendor/rwarasaurus/validation/src/ValidatorFactory.php(60): Validation\ValidatorFactory::rule('length', Array)
#4 /var/www/html/vendor/rwarasaurus/validation/src/ValidatorFactory.php(78): Validation\ValidatorFactory::addRulesWithOptions(Object(Validation\Validator), 'account_usernam...', Array)
#5 /var/www/html/vendor/rwarasaurus/validation/src/ValidatorFactory.php(17): Validation\ValidatorFactory::addRules(Object(Validation\Validator), 'account_usernam...', Array)
#6 /var/www/html/app/src/Controllers/Installer/Install.php(181): Validation\ValidatorFactory::create(Array, Array)
#7 /var/www/html/app/src/Kernel.php(36): Anchorcms\Controllers\Installer\Install->postAccount(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#8 /var/www/html/app/src/Middleware/Kernel.php(32): Anchorcms\Kernel->getResponse(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#9 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Anchorcms\Middleware\Kernel->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#10 /var/www/html/app/src/Middleware/Session.php(22): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Anchorcms\Middleware\Session->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#12 /var/www/html/app/src/Middleware/RedirectTrailingSlash.php(22): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#13 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Anchorcms\Middleware\RedirectTrailingSlash->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#14 /var/www/html/app/start.php(66): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#15 /var/www/html/vendor/ircmaxell/tari-php/lib/ServerMiddleware/CallableServerMiddleware.php(19): {closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#16 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Tari\ServerMiddleware\CallableServerMiddleware->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#17 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(75): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#18 /var/www/html/app/start.php(89): Tari\Server->run(Object(GuzzleHttp\Psr7\ServerRequest), Object(Closure))
#19 /var/www/html/web/index.php(8): require('/var/www/html/a...')
#20 {main}
```

Seem we're also missing a schema file for mysql:
```
ErrorException

file_get_contents(/var/www/html/app/resources/schema_mysql.sql): failed to open stream: No such file or directory in /var/www/html/app/src/Services/Installer.php:97

Stack Trace

#0 [internal function]: Anchorcms\Errors->native('2', 'file_get_conten...', '/var/www/html/a...', 97, Array)
#1 /var/www/html/app/src/Services/Installer.php(97): file_get_contents('/var/www/html/a...')
#2 /var/www/html/app/src/Services/Installer.php(58): Anchorcms\Services\Installer->runSchema(Object(PDO), Array)
#3 /var/www/html/app/src/Controllers/Installer/Install.php(200): Anchorcms\Services\Installer->run(Array, Object(Anchorcms\Services\Auth))
#4 /var/www/html/app/src/Kernel.php(36): Anchorcms\Controllers\Installer\Install->postAccount(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#5 /var/www/html/app/src/Middleware/Kernel.php(32): Anchorcms\Kernel->getResponse(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#6 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Anchorcms\Middleware\Kernel->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#7 /var/www/html/app/src/Middleware/Session.php(22): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Anchorcms\Middleware\Session->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#9 /var/www/html/app/src/Middleware/RedirectTrailingSlash.php(22): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Anchorcms\Middleware\RedirectTrailingSlash->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#11 /var/www/html/app/start.php(66): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/html/vendor/ircmaxell/tari-php/lib/ServerMiddleware/CallableServerMiddleware.php(19): {closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#13 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(64): Tari\ServerMiddleware\CallableServerMiddleware->handle(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#14 /var/www/html/vendor/ircmaxell/tari-php/lib/Server.php(75): class@anonymous->next(Object(GuzzleHttp\Psr7\ServerRequest))
#15 /var/www/html/app/start.php(89): Tari\Server->run(Object(GuzzleHttp\Psr7\ServerRequest), Object(Closure))
#16 /var/www/html/web/index.php(8): require('/var/www/html/a...')
#17 {main}
```

**Comment by daviddarnes** [comment]
Thanks for submitting this. Why are you using the development version may I ask? We recommend you use the download link from the main site, the main version is more stable [anchorcms.com](https://anchorcms.com/)

**Comment by chrissound** [comment]
Just wanted to try it out. Pretty excited so far!

**Comment by TheBrenny** [comment]
Just you wait until 1.0 comes out! :P

**Comment by daviddarnes** [comment]
@chrissound ah ok, in that case I think the team are aware of this? @TheBrenny, @rwarasaurus?

**Comment by TheBrenny** [comment]
Just realised, `develop` *is* the 1.0 branch... :confounded: Anyway, I did a quick PR to @rwarasaurus's Validator branch which should fix the first stack trace. If it gets merged, you'll need to recompose your Anchor install to get the fix.

Looking into the second stack trace now...

**Comment by daviddarnes** [comment]
@TheBrenny quality work 👌

**Comment by rwarasaurus** [comment]
Im still testing with sqlite before i build the mysql schema file

**Comment by TheBrenny** [comment]
@rwarasaurus, maintaining two schema files *could* be tedious... Keeping in mind that we only need to maintain two databases (for now?), would it be worth to create one schema file, and have it go through a Parser?

**Comment by rwarasaurus** [comment]
@TheBrenny yea i know, i haven't got around to implementing this yet ... http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/schema-representation.html

**Comment by TheBrenny** [comment]
Closing due to:
 1. Bug is fixed; and
 2. Not fully completed yet.
