### ISSUE TITLE
Cannot update metadata

### ISSUE THREAD

**Issue by VeeeneX** [anchorcms/anchor-cms#826]
I've triyng to update metadata of blog, when error occurred:
```text
// I did var_dump of values
array (size=9)
  'sitename' => string 'VeeeneX' (length=7)
  'description' => string 'It’s not just any blog. It’s an Anchor blog.' (length=48)
  'home_page' => string '1' (length=1)
  'posts_page' => string '1' (length=1)
  'posts_per_page' => string '8' (length=1)
  'auto_published_comments' => null
  'theme' => string 'danoxide-snowly' (length=15)
  'comment_notifications' => null // Problem occurs here
  'comment_moderation_keys' => string '0' (length=1)
Uncaught Exception

Database Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null

SQL: UPDATE `b_meta` SET `value` = ? WHERE `key` = ?

Origin

system\database\connector.php on line 52

Trace

#0 P:\webroot\Blog\system\database\query.php(217): System\Database\Connector->ask('UPDATE `b_meta`...', Array)
#1 P:\webroot\Blog\anchor\routes\metadata.php(53): System\Database\Query->update(Array)
#2 [internal function]: {closure}()
#3 P:\webroot\Blog\system\route.php(152): call_user_func_array(Object(Closure), Array)
#4 P:\webroot\Blog\system\router.php(152): System\Route->run()
#5 P:\webroot\Blog\system\start.php(36): System\Router->dispatch()
#6 P:\webroot\Blog\index.php(33): require('P:\\webroot\\Blog...')
#7 {main}
```
This happends on line 52 in `routes/metadata.php`
I had seen older issue that was similar to this.
But it's easy to fix:
Option 1:
```php
<?php
foreach($input as $key => $value) {
			$value = (!$value) ? 0 : $value;
			Query::table(Base::table('meta'))->where('key', '=', $key)->update(array('value' => $value));
		}
```
Or to fix it for future:
in system/database/builder.php on line 153
```php
<?php
foreach($row as $key => $value) {
			$placeholders[] = $this->wrap($key) . ' = ?';
			$values[] = (!$value) ? 0 : $value;
		}

```

**Comment by CraigChilds94** [comment]
Which version of Anchor do you have?

If you grab the current `0.9-dev` branch does it still happen, I'm not getting any problems with my version. And it should be released soon hopefully.

**Comment by VeeeneX** [comment]
Fixed with newest version

**Comment by CraigChilds94** [comment]
I thought it might have been. :)
