### ISSUE TITLE
Deleting top-level 'Posts' page crashes both website and CMS

### ISSUE THREAD

**Issue by foreste** [anchorcms/anchor-cms#874]
How to reproduce:

Login to the admin section of your site
Go to Pages
Go to the Posts page (ie, homepage)
Click 'Delete'

When viewing home page on the website:
```
Uncaught Exception

Trying to get property of non-object
Origin

anchor\routes\site.php on line 12
Trace

#0 C:\wamp\www\hsn\anchor\routes\site.php(12): System\Error::native(8, 'Trying to get p...', 'C:\\wamp\\www\\hsn...', 12, Array)
#1 C:\wamp\www\hsn\anchor\run.php(56): require('C:\\wamp\\www\\hsn...')
#2 C:\wamp\www\hsn\system\start.php(21): require('C:\\wamp\\www\\hsn...')
#3 C:\wamp\www\hsn\index.php(33): require('C:\\wamp\\www\\hsn...')
#4 {main}
```

when viewing any page in the CMS:
```
Uncaught Exception

Trying to get property of non-object
Origin

anchor\views\partials\header.php on line 47
Trace

#0 C:\wamp\www\hsn\anchor\views\partials\header.php(47): System\Error::native(8, 'Trying to get p...', 'C:\\wamp\\www\\hsn...', 47, Array)
#1 C:\wamp\www\hsn\system\view.php(87): require('C:\\wamp\\www\\hsn...')
#2 C:\wamp\www\hsn\system\view.php(72): System\View->render()
#3 C:\wamp\www\hsn\anchor\routes\posts.php(21): System\View->partial('header', 'partials/header')
#4 [internal function]: {closure}()
#5 C:\wamp\www\hsn\system\route.php(152): call_user_func_array(Object(Closure), Array)
#6 C:\wamp\www\hsn\system\router.php(152): System\Route->run()
#7 C:\wamp\www\hsn\system\start.php(36): System\Router->dispatch()
#8 C:\wamp\www\hsn\index.php(33): require('C:\\wamp\\www\\hsn...')
#9 {main}
```

I was able to fix this by going into the anchor_meta database table and changing the value of home_page and posts_page to the ID of an existing page

There should probably be some measure in place to prevent the user from getting in to this situation?

**Comment by daviddarnes** [comment]
You're right, but at the same time you shouldn't be deleting this page if it's the blog page. This issue has apparently been addressed in 0.9-dev https://github.com/anchorcms/anchor-cms/issues/616
