### ISSUE TITLE
Creating custom field returns error

### ISSUE THREAD

**Issue by Lewitje** [anchorcms/anchor-cms#895]
When trying to create a custom field **(dev 0.9)** I get this error:

htmlspecialchars() expects parameter 1 to be string, array given
The error has been logged in /anchor/errors.log
Uncaught Exception

htmlspecialchars() expects parameter 1 to be string, array given

Origin

system/helpers.php on line 79

Trace

#0 [internal function]: System\Error::native(2, 'htmlspecialchar...', '/Users/Lewi/Des...', 79, Array)
#1 /Users/Lewi/Desktop/my-site/system/helpers.php(79): htmlspecialchars(Array, 3, 'UTF-8', false)
#2 /Users/Lewi/Desktop/my-site/system/helpers.php(86): e(Array, 3)
#3 /Users/Lewi/Desktop/my-site/anchor/routes/fields.php(45): eq(Array)
#4 [internal function]: {closure}()
#5 /Users/Lewi/Desktop/my-site/system/route.php(152): call_user_func_array(Object(Closure), Array)
#6 /Users/Lewi/Desktop/my-site/system/router.php(152): System\Route->run()
#7 /Users/Lewi/Desktop/my-site/system/start.php(36): System\Router->dispatch()
#8 /Users/Lewi/Desktop/my-site/index.php(33): require('/Users/Lewi/Des...')
#9 {main}

**Comment by TheBrenny** [comment]
I had a feeling that this would do some strange things..... I'll see what I can do.

**Comment by TheBrenny** [comment]
This can now be closed as a fix has been merged: #908
