### ISSUE TITLE
Error when adding new page

### ISSUE THREAD

**Issue by a9tm** [anchorcms/anchor-cms#911]
I'm using 0.10 and this error happens when I was adding new page:

    Database Error: SQLSTATE[HY000]: General error: 1364 Field 'menu_order' doesn't have a default value
    SQL: INSERT INTO `anchor_pages` (`parent`, `name`, `title`, `slug`, `content`, `status`, `redirect`, `show_in_menu`, `pagetype`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)
    The error has been logged in /anchor/errors.log

    Uncaught Exception

    Database Error: SQLSTATE[HY000]: General error: 1364 Field 'menu_order' doesn't have a default value

    SQL: INSERT INTO `anchor_pages` (`parent`, `name`, `title`, `slug`, `content`, `status`, `redirect`, `show_in_menu`, `pagetype`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)

    Origin

    system/database/connector.php on line 52

    Trace

    #0 /usr/local/www/anchor/system/database/query.php(205): System\Database\Connector->ask('INSERT INTO `an...', Array)
    #1 [internal function]: System\Database\Query->insert_get_id(Array)
    #2 /usr/local/www/anchor/anchor/models/base.php(19): call_user_func_array(Array, Array)
    #3 /usr/local/www/anchor/system/database/record.php(136): Base::__callStatic('insert_get_id', Array)
    #4 /usr/local/www/anchor/system/database/record.php(136): Page::insert_get_id(Array)
    #5 /usr/local/www/anchor/anchor/routes/pages.php(208): System\Database\Record::create(Array)
    #6 [internal function]: {closure}()
    #7 /usr/local/www/anchor/system/route.php(152): call_user_func_array(Object(Closure), Array)
    #8 /usr/local/www/anchor/system/router.php(152): System\Route->run()
    #9 /usr/local/www/anchor/system/start.php(36): System\Router->dispatch()
    #10 /usr/local/www/anchor/index.php(33): require('/usr/local/www/...')
    #11 {main}

**Comment by TheBrenny** [comment]
What database are you using? Because I feel that this may be database related... You must be using MySQL or SQLite. My guess would be that you're not using an SQL server that anchor knows..

Follow these requirements: [AnchorCMS: Requirements](https://github.com/anchorcms/anchor-cms#requirements)

Which leads me to a further note that I haven't tested SQLite, and I'm not sure if anyone has, but that may not work 100%. Use MySQL. :+1:

**Comment by a9tm** [comment]
I have checked AnchorCMS requirements as well, I installed Mysql-server 5.6, and php 5.6.11 with packages list: php56, php56-pdo, php56-pdo_mysql, etc.

**Comment by fbrinker** [comment]
Had the same error, just fixed it by adding a default value. All fields should have default values in the future to prevent errors with missing fields in insert queries.

https://github.com/anchorcms/anchor-cms/pull/914

**Comment by EngBadr** [comment]
Hi , 
I find that the problem is in the menu_order field (NN) it is not accept the NULL value , So Just change it to accept Null altering the table 
~~~
ALTER TABLE anchor_pages CHANGE COLUMN menu_order  menu_order INT(4) NULL;
~~~
Of course it will be accepted to use the default value
