### ISSUE TITLE
Problem with SSL certificate when connecting to Admin

### ISSUE THREAD

**Issue by remyguillaume** [anchorcms/anchor-cms#937]
I cannot connect to the admin part of Anchor any more, because I get the following error : 

```
Uncaught Exception

file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Origin

anchor/libraries/update.php on line 55
Trace

#0 [internal function]: System\Error::native(2, 'file_get_conten...', '/homepages/1/XX...', 55, Array)
#1 /homepages/1/XX/htdocs/blog/anchor/libraries/update.php(55): file_get_contents('http://anchorcm...', false, Resource id #57)
#2 /homepages/1/XX/htdocs/blog/anchor/libraries/update.php(34): Update::touch()
#3 /homepages/1/XX/htdocs/blog/anchor/libraries/update.php(13): Update::renew()
#4 /homepages/1/XX/htdocs/blog/anchor/routes/admin.php(54): Update::version()
#5 [internal function]: {closure}()
#6 /homepages/1/XX/htdocs/blog/system/route.php(152): call_user_func_array(Object(Closure), Array)
#7 /homepages/1/XX/htdocs/blog/system/router.php(152): System\Route->run()
#8 /homepages/1/XX/htdocs/blog/system/start.php(36): System\Router->dispatch()
#9 /homepages/1/XX/htdocs/blog/index.php(33): require('/homepages/1/XX...')
#10 {main}
```

When  I look at update.config, this URL ist configured :+1: 
```
$url = 'http://anchorcms.com/version';
```

The webSite of Anchor automatically redirects to **https**://anchorcms.com/version, and this seems to be a problem for the file_get_contents() method

I have the problem with both PHP 5.5 and PHP 5.6.
I'm on a online shared server, and I cannot say if some change was made in the config of PHP.

Any Idea ?
Thanks !
Guillaume.

**Comment by CraigChilds94** [comment]
@remyguillaume What version of Anchor are you using?

**Comment by remyguillaume** [comment]
Version 0.9.2

**Comment by remyguillaume** [comment]
Hi there,

I found the following link : http://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more

And it seems that the following code in file update.php solved my problem :
I replaced

```
$context = stream_context_create(array('http' => array('timeout' => 2)));
```
by

```
$context = stream_context_create(array('http' => array('timeout' => 2),
					'ssl' => array('verify_peer' => false,	'verify_peer_name' => false)));
```

I can access the admin part of the website again, but I don't really understand the security consequences... And nor why this happend suddenly. Perhaps there was a change by 1&1.

Can somebody explain me if this is a correct solution, and why ?
Thanks !

**Comment by ruLait** [comment]
I have a same problem, but the error output code is slightly different:
```
file_get_contents(http://anchorcms.com/version): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

The error has been logged in /anchor/errors.log
Uncaught Exception

file_get_contents(http://anchorcms.com/version): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

Origin

anchor/libraries/update.php on line 55

Trace

#0 [internal function]: System\Error::native(2, 'file_get_conten...', '/home/www/id033...', 55, Array)
#1 /home/www/id0336/data/www/X/anchor/libraries/update.php(55): file_get_contents('http://anchorc...', false, Resource id #5)
#2 /home/www/X/data/www/X/anchor/libraries/update.php(18): Update::touch()
#3 /home/www/id0336/data/www/X/anchor/libraries/update.php(8): Update::setup()
#4 /home/www/id0336/data/www/X/anchor/routes/admin.php(59): Update::version()
#5 [internal function]: {closure}()
#6 /home/www/id0336/data/www/X/system/route.php(152): call_user_func_array(Object(Closure), Array)
#7 /home/www/id0336/data/www/X/system/router.php(152): System\Route->run()
#8 /home/www/id0336/data/www/X/system/start.php(36): System\Router->dispatch()
#9 /home/www/id0336/data/www/X/index.php(33): require('/home/www/id033...')
#10 {main}
```

**Comment by mrozycki** [comment]
DIsabling verification is generally not a good thing to do. I have no idea whether it is dangerous in this particular case, but why risk it?

For a proper solution, see this: http://stackoverflow.com/a/28701786

For a terribly hacky but safe solution, make the `Update::touch()` method just return "0.9.2".

**Comment by CraigChilds94** [comment]
@remyguillaume  If you pull `pre-1.0-develop` you shouldn't have this problem anymore?
