### ISSUE TITLE
Deleting home/posts page while in use causes exception

### ISSUE THREAD

**Issue by bennnn** [anchorcms/anchor-cms#945]
In the "Site Metadata" section under "Home page" and "Posts page" - if the page referred to here is deleted the following error occurs (there is no warning or anything to prevent you from doing so):

```
Uncaught Exception

Trying to get property of non-object

Origin

anchor/views/partials/header.php on line 47

Trace

#0 /home/www/anchor/views/partials/header.php(47): System\Error::native(8, 'Trying to get p...', '/home/www/ancho...', 47, Array)
#1 /home/www/system/view.php(87): require('/home/www/ancho...')
#2 /home/www/system/view.php(72): System\View->render()
#3 /home/www/anchor/routes/pages.php(21): System\View->partial('header', 'partials/header')
#4 [internal function]: {closure}()
#5 /home/www/system/route.php(152): call_user_func_array(Object(Closure), Array)
#6 /home/www/system/router.php(152): System\Route->run()
#7 /home/www/system/start.php(36): System\Router->dispatch()
#8 /home/www/index.php(33): require('/home/www/syste...')
#9 {main}
```

And also

```
Uncaught Exception

Trying to get property of non-object

Origin

anchor/routes/site.php on line 12

Trace

#0 /home/www/anchor/routes/site.php(12): System\Error::native(8, 'Trying to get p...', '/home/www/ancho...', 12, Array)
#1 /home/www/anchor/run.php(56): require('/home/www/ancho...')
#2 /home/www/system/start.php(21): require('/home/www/ancho...')
#3 /home/www/index.php(33): require('/home/www/syste...')
#4 {main}
```

If you manage to do this yourself you can fix it in your database, under `anchor_meta` set `home_page` and/or `posts_page` to an ID that exists.

**Comment by CraigChilds94** [comment]
@bennnn  What version of Anchor are you using?

**Comment by bennnn** [comment]
0.9.2 (version from your website), which I just realized is not the latest you have here on Github, so I apologize if you fixed it since!

**Comment by CraigChilds94** [comment]
@bennnn  Yeah I think I fixed it since, BUT we haven't had the time to push any new releases. If you dare, you could try the `0.10-dev` branch?

**Comment by bennnn** [comment]
Tried 0.10 but unfortunately no go

```
Uncaught Exception

Trying to get property of non-object

Origin

anchor/views/partials/header.php on line 47

Trace

#0 /home/www/anchor/views/partials/header.php(47): System\Error::native(8, 'Trying to get p...', '/home/www/ancho...', 47, Array)
#1 /home/www/system/view.php(87): require('/home/www/ancho...')
#2 /home/www/system/view.php(72): System\View->render()
#3 /home/www/anchor/routes/pages.php(21): System\View->partial('header', 'partials/header')
#4 [internal function]: {closure}()
#5 /home/www/system/route.php(152): call_user_func_array(Object(Closure), Array)
#6 /home/www/system/router.php(152): System\Route->run()
#7 /home/www/system/start.php(36): System\Router->dispatch()
#8 /home/www/index.php(33): require('/home/www/syste...')
#9 {main}
```

I will have a look at the source when I can, see if I can contribute a fix.

Many thanks!
